name: Django Project Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build with Docker Compose
      run: docker compose build

    - name: Start services with Docker Compose
      run: docker compose up -d

    - name: Wait for services to be ready
      run: sleep 30  # Adjust based on your service startup time

    - name: Run Tests
      run: docker compose exec -T backend sh -c "flake8 && pytest ."

    - name: Stop containers
      if: always()
      run: docker compose down
